// Generated by https://quicktype.io

export interface Propiedad {
    id:              number;
    valorCom:        number;
    nombrePropiedad: string;
    numHabitaciones: number;
    ubicacion:       string;
    numBanos:        number;
}
